NEI <- readRDS("exdata-data-NEI_data/summarySCC_PM25.rds")
SCC <- readRDS("exdata-data-NEI_data/Source_Classification_Code.rds")
baltimore_emission=subset(NEI,NEI$fips=="24510")
baltimore_source=tapply(baltimore_emission$Emissions,list(baltimore_emission$type,baltimore_emission$year),sum)
baltimore_source_df=as.data.frame(baltimore_source)
baltimore_source_df$type=rownames(baltimore_source_df)
library(tidyr)
baltimore_source_df_long=gather(baltimore_source_df,"year","total",1:4)
png("plot3_Project2.png",width=480,height=480)
ggplot(data = baltimore_source_df_long,aes(year,total))+geom_bar(stat="identity")+facet_wrap(~type,ncol = 4)+theme_bw()
dev.off()
